2022-08-30 15:28:09,866 ERROR 13912 [-/::1/-/60ms GET /] nodejs.ReferenceError: app is not defined
    at HomeController.index (H:\egg\myEgg\app\controller\home.js:7:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at next (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:45:18)
    at H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\router.js:186:18
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:36:12

pid: 13912
hostname: DESKTOP-9KLCLN9

2022-08-30 15:28:19,409 ERROR 13912 [-/::1/-/54ms GET /] nodejs.ReferenceError: app is not defined
    at HomeController.index (H:\egg\myEgg\app\controller\home.js:7:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at next (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:45:18)
    at H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\router.js:186:18
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:36:12

pid: 13912
hostname: DESKTOP-9KLCLN9

2022-08-30 16:09:51,168 ERROR 14708 [-/::1/-/3ms GET /insertUser] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '2' for key 'PRIMARY'
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(2, '李四', 20)
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '2' for key 'PRIMARY'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(2, '李四', 20)"
name: "ER_DUP_ENTRYError"
pid: 14708
hostname: DESKTOP-9KLCLN9

2022-08-30 16:10:02,085 ERROR 14708 [-/::1/-/2ms GET /insertUser] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '2' for key 'PRIMARY'
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(2, '李四', 20)
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '2' for key 'PRIMARY'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(2, '李四', 20)"
name: "ER_DUP_ENTRYError"
pid: 14708
hostname: DESKTOP-9KLCLN9

2022-08-30 16:13:56,445 ERROR 2516 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 2516
hostname: DESKTOP-9KLCLN9

2022-08-30 16:16:36,274 ERROR 2516 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 2516
hostname: DESKTOP-9KLCLN9

2022-08-30 16:16:50,751 ERROR 6524 [-/::1/-/12ms GET /insertUser] nodejs.ER_BAD_NULL_ERRORError: ER_BAD_NULL_ERROR: Column 'id' cannot be null
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(NULL, NULL, NULL)
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'id' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(NULL, NULL, NULL)"
name: "ER_BAD_NULL_ERRORError"
pid: 6524
hostname: DESKTOP-9KLCLN9

2022-08-30 16:16:55,276 ERROR 6524 [-/::1/-/2ms GET /insertUser] nodejs.ER_BAD_NULL_ERRORError: ER_BAD_NULL_ERROR: Column 'id' cannot be null
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(NULL, NULL, NULL)
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'id' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(NULL, NULL, NULL)"
name: "ER_BAD_NULL_ERRORError"
pid: 6524
hostname: DESKTOP-9KLCLN9

2022-08-30 16:16:57,735 ERROR 6524 [-/::1/-/2ms GET /insertUser] nodejs.ER_BAD_NULL_ERRORError: ER_BAD_NULL_ERROR: Column 'id' cannot be null
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(NULL, NULL, NULL)
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'id' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `userInfo`(`id`, `name`, `age`) VALUES(NULL, NULL, NULL)"
name: "ER_BAD_NULL_ERRORError"
pid: 6524
hostname: DESKTOP-9KLCLN9

2022-08-30 16:18:32,778 ERROR 2516 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 2516
hostname: DESKTOP-9KLCLN9

2022-09-21 10:26:49,788 ERROR 2828 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 2828
hostname: DESKTOP-9KLCLN9

2022-09-21 19:25:29,675 ERROR 14904 [-/127.0.0.1/-/69ms GET /getUserInfo?id=1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: SELECT * FROM `user_info` WHERE `id` = '1' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user_info` WHERE `id` = '1' LIMIT 0, 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 14904
hostname: DESKTOP-9KLCLN9

2022-09-21 19:25:40,366 ERROR 14904 [-/127.0.0.1/-/49ms GET /getUserInfo?user_id=1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
    at Query.Sequence._packetToError (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (H:\egg\myEgg\node_modules\.pnpm\mysql@2.18.1\node_modules\mysql\lib\Pool.js:199:23)
    at H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (H:\egg\myEgg\node_modules\.pnpm\pify@2.3.0\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (H:\egg\myEgg\node_modules\.pnpm\ali-rds@3.4.0\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:65:19)
    at H:\egg\myEgg\node_modules\.pnpm\co@4.6.0\node_modules\co\index.js:54:5
    sql: SELECT * FROM `user_info` WHERE `id` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user_info` WHERE `id` IS NULL LIMIT 0, 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 14904
hostname: DESKTOP-9KLCLN9

2022-09-21 21:31:47,986 ERROR 12024 nodejs.ClusterClientNoResponseError: client no response in 3951192ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (H:\egg\myEgg\node_modules\.pnpm\cluster-client@3.1.1\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 12024
hostname: DESKTOP-9KLCLN9

2022-09-21 21:37:10,929 ERROR 12024 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 12024
hostname: DESKTOP-9KLCLN9

2022-09-21 21:43:20,941 ERROR 3572 [-/127.0.0.1/-/11ms POST /login] nodejs.TypeError: Cannot destructure property 'user_number' of 'ctx.body' as it is undefined.
    at userInfo.login (H:\egg\myEgg\app\controller\userInfo.js:6:13)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at next (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:45:18)
    at H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\router.js:186:18
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:36:12

pid: 3572
hostname: DESKTOP-9KLCLN9

2022-09-21 21:43:34,578 ERROR 13104 [-/127.0.0.1/-/13ms POST /login] nodejs.TypeError: Cannot destructure property 'user_number' of 'ctx.body' as it is undefined.
    at userInfo.login (H:\egg\myEgg\app\controller\userInfo.js:6:13)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at next (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:45:18)
    at H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\router.js:186:18
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:36:12

pid: 13104
hostname: DESKTOP-9KLCLN9

2022-09-21 22:31:25,043 ERROR 9092 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 9092
hostname: DESKTOP-9KLCLN9

2022-09-21 22:59:44,987 ERROR 9092 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 9092
hostname: DESKTOP-9KLCLN9

2022-09-21 23:41:49,767 ERROR 8288 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 8288
hostname: DESKTOP-9KLCLN9

2022-09-21 23:44:47,230 ERROR 2836 nodejs.EPERMError: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
errno: -4048
syscall: "watch"
code: "EPERM"
filename: null
dir: "H:\\egg\\myEgg\\app\\view\\news"
name: "EPERMError"
pid: 2836
hostname: DESKTOP-9KLCLN9

2022-09-21 23:44:47,235 ERROR 2836 nodejs.EPERMError: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
errno: -4048
syscall: "watch"
code: "EPERM"
filename: null
dir: "H:\\egg\\myEgg\\app\\view"
name: "EPERMError"
pid: 2836
hostname: DESKTOP-9KLCLN9

2022-09-21 23:48:27,600 ERROR 9080 [-/127.0.0.1/-/9ms POST /removeUser] nodejs.TypeError: ctx.service.removeUser is not a function
    at userInfo.removeUser (H:\egg\myEgg\app\controller\userInfo.js:122:38)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at next (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:45:18)
    at middleware (H:\egg\myEgg\node_modules\.pnpm\koa-jwt2@1.0.3\node_modules\koa-jwt2\lib\index.js:145:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async H:\egg\myEgg\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50

pid: 9080
hostname: DESKTOP-9KLCLN9

2022-09-21 23:49:01,669 ERROR 1536 [-/127.0.0.1/-/23ms POST /removeUser] nodejs.TypeError: ctx.service.removeOne is not a function
    at userInfo.removeUser (H:\egg\myEgg\app\controller\userInfo.js:122:38)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (H:\egg\myEgg\node_modules\.pnpm\egg-core@4.23.0\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (H:\egg\myEgg\node_modules\.pnpm\@eggjs+router@2.0.1\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:44:32)
    at next (H:\egg\myEgg\node_modules\.pnpm\koa-compose@3.2.1\node_modules\koa-compose\index.js:45:18)
    at middleware (H:\egg\myEgg\node_modules\.pnpm\koa-jwt2@1.0.3\node_modules\koa-jwt2\lib\index.js:145:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async H:\egg\myEgg\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50

pid: 1536
hostname: DESKTOP-9KLCLN9

2022-09-21 23:52:33,693 ERROR 2836 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 2836
hostname: DESKTOP-9KLCLN9

2022-09-21 23:55:41,529 ERROR 2836 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
errno: -4077
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 2836
hostname: DESKTOP-9KLCLN9

